# ============================================================================
# cave-completions.fish — GENERATED by gen-fish-completions.sh — do not edit
# ============================================================================
# Regenerate:  fish/scripts/gen-fish-completions.sh
# Verify:      fish/scripts/gen-fish-completions.sh --check
# Loaded automatically by fish/cave-scripts.fish.
#
# Directive groups are positional: group N completes argument N (the same
# corrected contract as the bash completions since the 2026-09-05 fix).
# <name> groups are dynamic sources resolved lazily at completion time.
# ============================================================================

function __cave_arg_pos --description '0-based index of the argument being completed (flags skipped)'
    set -l tokens (commandline -opc)
    set -e tokens[1]
    set -l pos 0
    for t in $tokens
        switch $t
            case '-*'
            case '*'
                set pos (math $pos + 1)
        end
    end
    # When completing a new word the cursor sits on an empty token; the
    # tokens list already excludes the command itself, so the position of
    # the argument being completed is (count of prior non-flag args).
    echo $pos
end

# cave-activity-feed
complete -f  -c cave-activity-feed -c stack-activity-feed -k -a '(__cave_complete "cave-activity-feed" (__cave_arg_pos))'

# cave-arr
complete -f  -c cave-arr -c stack-arr -k -a '(__cave_complete "cave-arr" (__cave_arg_pos))'

# cave-arr-backlog
complete -f  -c cave-arr-backlog -c stack-arr-backlog -k -a '(__cave_complete "cave-arr-backlog" (__cave_arg_pos))'

# cave-arr-blocklist
complete -f  -c cave-arr-blocklist -c stack-arr-blocklist -k -a '(__cave_complete "cave-arr-blocklist" (__cave_arg_pos))'

# cave-arr-clear-blocklist
complete -f  -c cave-arr-clear-blocklist -c stack-arr-clear-blocklist -k -a '(__cave_complete "cave-arr-clear-blocklist" (__cave_arg_pos))'

# cave-arr-import
complete -f  -c cave-arr-import -c stack-arr-import -k -a '(__cave_complete "cave-arr-import" (__cave_arg_pos))'

# cave-arr-import-all
complete -f  -c cave-arr-import-all -c stack-arr-import-all -k -a '(__cave_complete "cave-arr-import-all" (__cave_arg_pos))'

# cave-arr-import-candidates
complete -f  -c cave-arr-import-candidates -c stack-arr-import-candidates -k -a '(__cave_complete "cave-arr-import-candidates" (__cave_arg_pos))'

# cave-arr-import-starvation
complete -f  -c cave-arr-import-starvation -c stack-arr-import-starvation -k -a '(__cave_complete "cave-arr-import-starvation" (__cave_arg_pos))'

# cave-arr-logs
complete -f  -c cave-arr-logs -c stack-arr-logs -k -a '(__cave_complete "cave-arr-logs" (__cave_arg_pos))'

# cave-arr-missing-aired
complete -f  -c cave-arr-missing-aired -c stack-arr-missing-aired -k -a '(__cave_complete "cave-arr-missing-aired" (__cave_arg_pos))'

# cave-arr-queue-errors
complete -f  -c cave-arr-queue-errors -c stack-arr-queue-errors -k -a '(__cave_complete "cave-arr-queue-errors" (__cave_arg_pos))'

# cave-arr-recently-added
complete -f  -c cave-arr-recently-added -c stack-arr-recently-added -k -a '(__cave_complete "cave-arr-recently-added" (__cave_arg_pos))'

# cave-arr-toggle-search
complete -f  -c cave-arr-toggle-search -c stack-arr-toggle-search -k -a '(__cave_complete "cave-arr-toggle-search" (__cave_arg_pos))'

# cave-arrival-notify
complete -f  -c cave-arrival-notify -c stack-arrival-notify -k -a '(__cave_complete "cave-arrival-notify" (__cave_arg_pos))'

# cave-audit-residue
complete -f  -c cave-audit-residue -c stack-audit-residue -k -a '(__cave_complete "cave-audit-residue" (__cave_arg_pos))'

# cave-backlog-status
complete -f  -c cave-backlog-status -c stack-backlog-status -k -a '(__cave_complete "cave-backlog-status" (__cave_arg_pos))'

# cave-btrfs-balance
complete -f  -c cave-btrfs-balance -k -a '(__cave_complete "cave-btrfs-balance" (__cave_arg_pos))'

# cave-btrfs-balance-status
complete -f  -c cave-btrfs-balance-status -k -a '(__cave_complete "cave-btrfs-balance-status" (__cave_arg_pos))'

# cave-btrfs-device-stats
complete -f  -c cave-btrfs-device-stats -k -a '(__cave_complete "cave-btrfs-device-stats" (__cave_arg_pos))'

# cave-btrfs-qgroup
complete -f  -c cave-btrfs-qgroup -k -a '(__cave_complete "cave-btrfs-qgroup" (__cave_arg_pos))'

# cave-btrfs-scrub
complete -f  -c cave-btrfs-scrub -k -a '(__cave_complete "cave-btrfs-scrub" (__cave_arg_pos))'

# cave-btrfs-scrub-status
complete -f  -c cave-btrfs-scrub-status -k -a '(__cave_complete "cave-btrfs-scrub-status" (__cave_arg_pos))'

# cave-btrfs-snapper
complete -f  -c cave-btrfs-snapper -k -a '(__cave_complete "cave-btrfs-snapper" (__cave_arg_pos))'

# cave-btrfs-snapshot
complete -f  -c cave-btrfs-snapshot -k -a '(__cave_complete "cave-btrfs-snapshot" (__cave_arg_pos))'

# cave-btrfs-subvol
complete -f  -c cave-btrfs-subvol -k -a '(__cave_complete "cave-btrfs-subvol" (__cave_arg_pos))'

# cave-btrfs-subvolumes
complete -f  -c cave-btrfs-subvolumes -k -a '(__cave_complete "cave-btrfs-subvolumes" (__cave_arg_pos))'

# cave-btrfs-usage
complete -f  -c cave-btrfs-usage -k -a '(__cave_complete "cave-btrfs-usage" (__cave_arg_pos))'

# cave-claude-full-backup
complete -f  -c cave-claude-full-backup -c stack-claude-full-backup -k -a '(__cave_complete "cave-claude-full-backup" (__cave_arg_pos))'

# cave-command-queue-summary
complete -f  -c cave-command-queue-summary -c stack-command-queue-summary -k -a '(__cave_complete "cave-command-queue-summary" (__cave_arg_pos))'

# cave-config-drift
complete -f  -c cave-config-drift -c stack-config-drift -k -a '(__cave_complete "cave-config-drift" (__cave_arg_pos))'

# cave-container
complete -f  -c cave-container -c stack-container -k -a '(__cave_complete "cave-container" (__cave_arg_pos))'

# cave-cutoff-unmet
complete -f  -c cave-cutoff-unmet -c stack-cutoff-unmet -k -a '(__cave_complete "cave-cutoff-unmet" (__cave_arg_pos))'

# cave-disk-config-sizes
complete -f  -c cave-disk-config-sizes -c stack-disk-config-sizes -k -a '(__cave_complete "cave-disk-config-sizes" (__cave_arg_pos))'

# cave-disk-reclaim
complete -f  -c cave-disk-reclaim -c stack-disk-reclaim -k -a '(__cave_complete "cave-disk-reclaim" (__cave_arg_pos))'

# cave-docker-disk-usage
complete -f  -c cave-docker-disk-usage -c stack-docker-disk-usage -k -a '(__cave_complete "cave-docker-disk-usage" (__cave_arg_pos))'

# cave-help
complete -f  -c cave-help -c stack-help -k -a '(__cave_complete "cave-help" (__cave_arg_pos))'

# cave-image-check
complete -f  -c cave-image-check -c stack-image-check -k -a '(__cave_complete "cave-image-check" (__cave_arg_pos))'

# cave-import-lists
complete -f  -c cave-import-lists -c stack-import-lists -k -a '(__cave_complete "cave-import-lists" (__cave_arg_pos))'

# cave-letterboxd-history
complete -f  -c cave-letterboxd-history -c stack-letterboxd-history -k -a '(__cave_complete "cave-letterboxd-history" (__cave_arg_pos))'

# cave-letterboxd-import
complete -f  -c cave-letterboxd-import -c stack-letterboxd-import -k -a '(__cave_complete "cave-letterboxd-import" (__cave_arg_pos))'

# cave-letterboxd-track
complete -f  -c cave-letterboxd-track -c stack-letterboxd-track -k -a '(__cave_complete "cave-letterboxd-track" (__cave_arg_pos))'

# cave-letterboxd-tracked
complete -f  -c cave-letterboxd-tracked -c stack-letterboxd-tracked -k -a '(__cave_complete "cave-letterboxd-tracked" (__cave_arg_pos))'

# cave-letterboxd-untrack
complete -f  -c cave-letterboxd-untrack -c stack-letterboxd-untrack -k -a '(__cave_complete "cave-letterboxd-untrack" (__cave_arg_pos))'

# cave-log-levels
complete -f  -c cave-log-levels -c stack-log-levels -k -a '(__cave_complete "cave-log-levels" (__cave_arg_pos))'

# cave-loop-candidates
complete -f  -c cave-loop-candidates -c stack-loop-candidates -k -a '(__cave_complete "cave-loop-candidates" (__cave_arg_pos))'

# cave-loop-exclude
complete -f  -c cave-loop-exclude -c stack-loop-exclude -k -a '(__cave_complete "cave-loop-exclude" (__cave_arg_pos))'

# cave-loop-unmonitor
complete -f  -c cave-loop-unmonitor -c stack-loop-unmonitor -k -a '(__cave_complete "cave-loop-unmonitor" (__cave_arg_pos))'

# cave-maintenance-digest
complete -f  -c cave-maintenance-digest -c stack-maintenance-digest -k -a '(__cave_complete "cave-maintenance-digest" (__cave_arg_pos))'

# cave-mdblist-history
complete -f  -c cave-mdblist-history -c stack-mdblist-history -k -a '(__cave_complete "cave-mdblist-history" (__cave_arg_pos))'

# cave-mdblist-import
complete -f  -c cave-mdblist-import -c stack-mdblist-import -k -a '(__cave_complete "cave-mdblist-import" (__cave_arg_pos))'

# cave-mdblist-track
complete -f  -c cave-mdblist-track -c stack-mdblist-track -k -a '(__cave_complete "cave-mdblist-track" (__cave_arg_pos))'

# cave-mdblist-tracked
complete -f  -c cave-mdblist-tracked -c stack-mdblist-tracked -k -a '(__cave_complete "cave-mdblist-tracked" (__cave_arg_pos))'

# cave-mdblist-untrack
complete -f  -c cave-mdblist-untrack -c stack-mdblist-untrack -k -a '(__cave_complete "cave-mdblist-untrack" (__cave_arg_pos))'

# cave-mount-health
complete -f  -c cave-mount-health -c stack-mount-health -k -a '(__cave_complete "cave-mount-health" (__cave_arg_pos))'

# cave-notify-test
complete -f  -c cave-notify-test -c stack-notify-test -k -a '(__cave_complete "cave-notify-test" (__cave_arg_pos))'

# cave-nzbdav-dedup-check
complete -f  -c cave-nzbdav-dedup-check -c stack-nzbdav-dedup-check -k -a '(__cave_complete "cave-nzbdav-dedup-check" (__cave_arg_pos))'

# cave-nzbdav-delete-failures
complete -f  -c cave-nzbdav-delete-failures -c stack-nzbdav-delete-failures -k -a '(__cave_complete "cave-nzbdav-delete-failures" (__cave_arg_pos))'

# cave-nzbdav-history
complete -f  -c cave-nzbdav-history -c stack-nzbdav-history -k -a '(__cave_complete "cave-nzbdav-history" (__cave_arg_pos))'

# cave-nzbdav-queue
complete -f  -c cave-nzbdav-queue -c stack-nzbdav-queue -k -a '(__cave_complete "cave-nzbdav-queue" (__cave_arg_pos))'

# cave-nzbdav-stats
complete -f  -c cave-nzbdav-stats -c stack-nzbdav-stats -k -a '(__cave_complete "cave-nzbdav-stats" (__cave_arg_pos))'

# cave-oom-check
complete -f  -c cave-oom-check -c stack-oom-check -k -a '(__cave_complete "cave-oom-check" (__cave_arg_pos))'

# cave-perms-check
complete -f  -c cave-perms-check -c stack-perms-check -k -a '(__cave_complete "cave-perms-check" (__cave_arg_pos))'

# cave-plex
complete -f  -c cave-plex -c stack-plex -k -a '(__cave_complete "cave-plex" (__cave_arg_pos))'

# cave-plex-analyze
complete -f  -c cave-plex-analyze -c stack-plex-analyze -k -a '(__cave_complete "cave-plex-analyze" (__cave_arg_pos))'

# cave-plex-automatic-updates
complete -f  -c cave-plex-automatic-updates -c stack-plex-automatic-updates -k -a '(__cave_complete "cave-plex-automatic-updates" (__cave_arg_pos))'

# cave-plex-backup-database
complete -f  -c cave-plex-backup-database -c stack-plex-backup-database -k -a '(__cave_complete "cave-plex-backup-database" (__cave_arg_pos))'

# cave-plex-butler
complete -f  -c cave-plex-butler -c stack-plex-butler -k -a '(__cave_complete "cave-plex-butler" (__cave_arg_pos))'

# cave-plex-butler-all
complete -f  -c cave-plex-butler-all -c stack-plex-butler-all -k -a '(__cave_complete "cave-plex-butler-all" (__cave_arg_pos))'

# cave-plex-clean-cache-files
complete -f  -c cave-plex-clean-cache-files -c stack-plex-clean-cache-files -k -a '(__cave_complete "cave-plex-clean-cache-files" (__cave_arg_pos))'

# cave-plex-clean-log-files
complete -f  -c cave-plex-clean-log-files -c stack-plex-clean-log-files -k -a '(__cave_complete "cave-plex-clean-log-files" (__cave_arg_pos))'

# cave-plex-deep-media-analysis
complete -f  -c cave-plex-deep-media-analysis -c stack-plex-deep-media-analysis -k -a '(__cave_complete "cave-plex-deep-media-analysis" (__cave_arg_pos))'

# cave-plex-duplicates
complete -f  -c cave-plex-duplicates -c stack-plex-duplicates -k -a '(__cave_complete "cave-plex-duplicates" (__cave_arg_pos))'

# cave-plex-empty-trash
complete -f  -c cave-plex-empty-trash -c stack-plex-empty-trash -k -a '(__cave_complete "cave-plex-empty-trash" (__cave_arg_pos))'

# cave-plex-garbage-collect-blobs
complete -f  -c cave-plex-garbage-collect-blobs -c stack-plex-garbage-collect-blobs -k -a '(__cave_complete "cave-plex-garbage-collect-blobs" (__cave_arg_pos))'

# cave-plex-garbage-collect-media
complete -f  -c cave-plex-garbage-collect-media -c stack-plex-garbage-collect-media -k -a '(__cave_complete "cave-plex-garbage-collect-media" (__cave_arg_pos))'

# cave-plex-generate-ad-markers
complete -f  -c cave-plex-generate-ad-markers -c stack-plex-generate-ad-markers -k -a '(__cave_complete "cave-plex-generate-ad-markers" (__cave_arg_pos))'

# cave-plex-generate-chapter-thumbs
complete -f  -c cave-plex-generate-chapter-thumbs -c stack-plex-generate-chapter-thumbs -k -a '(__cave_complete "cave-plex-generate-chapter-thumbs" (__cave_arg_pos))'

# cave-plex-generate-credits-markers
complete -f  -c cave-plex-generate-credits-markers -c stack-plex-generate-credits-markers -k -a '(__cave_complete "cave-plex-generate-credits-markers" (__cave_arg_pos))'

# cave-plex-generate-intro-markers
complete -f  -c cave-plex-generate-intro-markers -c stack-plex-generate-intro-markers -k -a '(__cave_complete "cave-plex-generate-intro-markers" (__cave_arg_pos))'

# cave-plex-generate-media-index
complete -f  -c cave-plex-generate-media-index -c stack-plex-generate-media-index -k -a '(__cave_complete "cave-plex-generate-media-index" (__cave_arg_pos))'

# cave-plex-generate-voice-activity
complete -f  -c cave-plex-generate-voice-activity -c stack-plex-generate-voice-activity -k -a '(__cave_complete "cave-plex-generate-voice-activity" (__cave_arg_pos))'

# cave-plex-image-clean
complete -f  -c cave-plex-image-clean -c stack-plex-image-clean -k -a '(__cave_complete "cave-plex-image-clean" (__cave_arg_pos))'

# cave-plex-libraries
complete -f  -c cave-plex-libraries -c stack-plex-libraries -k -a '(__cave_complete "cave-plex-libraries" (__cave_arg_pos))'

# cave-plex-loudness-analysis
complete -f  -c cave-plex-loudness-analysis -c stack-plex-loudness-analysis -k -a '(__cave_complete "cave-plex-loudness-analysis" (__cave_arg_pos))'

# cave-plex-markers
complete -f  -c cave-plex-markers -c stack-plex-markers -k -a '(__cave_complete "cave-plex-markers" (__cave_arg_pos))'

# cave-plex-music-analysis
complete -f  -c cave-plex-music-analysis -c stack-plex-music-analysis -k -a '(__cave_complete "cave-plex-music-analysis" (__cave_arg_pos))'

# cave-plex-process-assets
complete -f  -c cave-plex-process-assets -c stack-plex-process-assets -k -a '(__cave_complete "cave-plex-process-assets" (__cave_arg_pos))'

# cave-plex-recently-added
complete -f  -c cave-plex-recently-added -c stack-plex-recently-added -k -a '(__cave_complete "cave-plex-recently-added" (__cave_arg_pos))'

# cave-plex-refresh-epg
complete -f  -c cave-plex-refresh-epg -c stack-plex-refresh-epg -k -a '(__cave_complete "cave-plex-refresh-epg" (__cave_arg_pos))'

# cave-plex-refresh-libraries
complete -f  -c cave-plex-refresh-libraries -c stack-plex-refresh-libraries -k -a '(__cave_complete "cave-plex-refresh-libraries" (__cave_arg_pos))'

# cave-plex-refresh-local-media
complete -f  -c cave-plex-refresh-local-media -c stack-plex-refresh-local-media -k -a '(__cave_complete "cave-plex-refresh-local-media" (__cave_arg_pos))'

# cave-plex-sessions
complete -f  -c cave-plex-sessions -c stack-plex-sessions -k -a '(__cave_complete "cave-plex-sessions" (__cave_arg_pos))'

# cave-plex-updates
complete -f  -c cave-plex-updates -c stack-plex-updates -k -a '(__cave_complete "cave-plex-updates" (__cave_arg_pos))'

# cave-plex-upgrade-media-analysis
complete -f  -c cave-plex-upgrade-media-analysis -c stack-plex-upgrade-media-analysis -k -a '(__cave_complete "cave-plex-upgrade-media-analysis" (__cave_arg_pos))'

# cave-prowlarr-indexers
complete -f  -c cave-prowlarr-indexers -c stack-prowlarr-indexers -k -a '(__cave_complete "cave-prowlarr-indexers" (__cave_arg_pos))'

# cave-queue-autofix
complete -f  -c cave-queue-autofix -c stack-queue-autofix -k -a '(__cave_complete "cave-queue-autofix" (__cave_arg_pos))'

# cave-queue-status
complete -f  -c cave-queue-status -c stack-queue-status -k -a '(__cave_complete "cave-queue-status" (__cave_arg_pos))'

# cave-radarr-health
complete -f  -c cave-radarr-health -c stack-radarr-health -k -a '(__cave_complete "cave-radarr-health" (__cave_arg_pos))'

# cave-radarr-prune
complete -f  -c cave-radarr-prune -c stack-radarr-prune -k -a '(__cave_complete "cave-radarr-prune" (__cave_arg_pos))'

# cave-rating-imdb
complete -f  -c cave-rating-imdb -c stack-rating-imdb -k -a '(__cave_complete "cave-rating-imdb" (__cave_arg_pos))'

# cave-rating-mdblist
complete -f  -c cave-rating-mdblist -c stack-rating-mdblist -k -a '(__cave_complete "cave-rating-mdblist" (__cave_arg_pos))'

# cave-recent
complete -f  -c cave-recent -c stack-recent -k -a '(__cave_complete "cave-recent" (__cave_arg_pos))'

# cave-requests
complete -f  -c cave-requests -c stack-requests -k -a '(__cave_complete "cave-requests" (__cave_arg_pos))'

# cave-resource-check
complete -f  -c cave-resource-check -c stack-resource-check -k -a '(__cave_complete "cave-resource-check" (__cave_arg_pos))'

# cave-restart-all
complete -f  -c cave-restart-all -c stack-restart-all -k -a '(__cave_complete "cave-restart-all" (__cave_arg_pos))'

# cave-seerr-requests
complete -f  -c cave-seerr-requests -c stack-seerr-requests -k -a '(__cave_complete "cave-seerr-requests" (__cave_arg_pos))'

# cave-sonarr-fix-episode-monitoring
complete -f  -c cave-sonarr-fix-episode-monitoring -c stack-sonarr-fix-episode-monitoring -k -a '(__cave_complete "cave-sonarr-fix-episode-monitoring" (__cave_arg_pos))'

# cave-sonarr-prune
complete -f  -c cave-sonarr-prune -c stack-sonarr-prune -k -a '(__cave_complete "cave-sonarr-prune" (__cave_arg_pos))'

# cave-status
complete -f  -c cave-status -c stack-status -k -a '(__cave_complete "cave-status" (__cave_arg_pos))'

# cave-sys-aur-audit
complete -f  -c cave-sys-aur-audit -c stack-aur-audit -k -a '(__cave_complete "cave-sys-aur-audit" (__cave_arg_pos))'

# cave-sys-claude-home
complete -f  -c cave-sys-claude-home -c stack-claude-home -k -a '(__cave_complete "cave-sys-claude-home" (__cave_arg_pos))'

# cave-sys-cron-list
complete -f  -c cave-sys-cron-list -c stack-cron-list -k -a '(__cave_complete "cave-sys-cron-list" (__cave_arg_pos))'

# cave-sys-disk-free
complete -f  -c cave-sys-disk-free -c stack-disk-free -k -a '(__cave_complete "cave-sys-disk-free" (__cave_arg_pos))'

# cave-sys-disk-health
complete -f  -c cave-sys-disk-health -c stack-disk-health -k -a '(__cave_complete "cave-sys-disk-health" (__cave_arg_pos))'

# cave-sys-firewall-status
complete -f  -c cave-sys-firewall-status -c stack-firewall-status -k -a '(__cave_complete "cave-sys-firewall-status" (__cave_arg_pos))'

# cave-sys-flatpak-updates
complete -f  -c cave-sys-flatpak-updates -c stack-flatpak-updates -k -a '(__cave_complete "cave-sys-flatpak-updates" (__cave_arg_pos))'

# cave-sys-git-status-all
complete -f  -c cave-sys-git-status-all -c stack-git-status-all -k -a '(__cave_complete "cave-sys-git-status-all" (__cave_arg_pos))'

# cave-sys-journal-errors
complete -f  -c cave-sys-journal-errors -c stack-journal-errors -k -a '(__cave_complete "cave-sys-journal-errors" (__cave_arg_pos))'

# cave-sys-journal-size
complete -f  -c cave-sys-journal-size -c stack-journal-size -k -a '(__cave_complete "cave-sys-journal-size" (__cave_arg_pos))'

# cave-sys-kernel-check
complete -f  -c cave-sys-kernel-check -c stack-kernel-check -k -a '(__cave_complete "cave-sys-kernel-check" (__cave_arg_pos))'

# cave-sys-mem-pressure
complete -f  -c cave-sys-mem-pressure -c stack-mem-pressure -k -a '(__cave_complete "cave-sys-mem-pressure" (__cave_arg_pos))'

# cave-sys-pkg-clean-cache
complete -f  -c cave-sys-pkg-clean-cache -c stack-pkg-clean-cache -k -a '(__cave_complete "cave-sys-pkg-clean-cache" (__cave_arg_pos))'

# cave-sys-pkg-history
complete -f  -c cave-sys-pkg-history -c stack-pkg-history -k -a '(__cave_complete "cave-sys-pkg-history" (__cave_arg_pos))'

# cave-sys-pkg-orphans
complete -f  -c cave-sys-pkg-orphans -c stack-pkg-orphans -k -a '(__cave_complete "cave-sys-pkg-orphans" (__cave_arg_pos))'

# cave-sys-pkg-update
complete -f  -c cave-sys-pkg-update -c stack-pkg-update -k -a '(__cave_complete "cave-sys-pkg-update" (__cave_arg_pos))'

# cave-sys-pkg-updates
complete -f  -c cave-sys-pkg-updates -c stack-pkg-updates -k -a '(__cave_complete "cave-sys-pkg-updates" (__cave_arg_pos))'

# cave-sys-reboot-check
complete -f  -c cave-sys-reboot-check -c stack-reboot-check -k -a '(__cave_complete "cave-sys-reboot-check" (__cave_arg_pos))'

# cave-sys-service-failed
complete -f  -c cave-sys-service-failed -c stack-service-failed -k -a '(__cave_complete "cave-sys-service-failed" (__cave_arg_pos))'

# cave-sys-ssh-doctor
complete -f  -c cave-sys-ssh-doctor -c stack-ssh-doctor -k -a '(__cave_complete "cave-sys-ssh-doctor" (__cave_arg_pos))'

# cave-sys-timer-status
complete -f  -c cave-sys-timer-status -c stack-timer-status -k -a '(__cave_complete "cave-sys-timer-status" (__cave_arg_pos))'

# cave-sys-uptime-report
complete -f  -c cave-sys-uptime-report -c stack-uptime-report -k -a '(__cave_complete "cave-sys-uptime-report" (__cave_arg_pos))'

# cave-sys-zombie-check
complete -f  -c cave-sys-zombie-check -c stack-zombie-check -k -a '(__cave_complete "cave-sys-zombie-check" (__cave_arg_pos))'

# cave-tmdb-missing
complete -f  -c cave-tmdb-missing -c stack-tmdb-missing -k -a '(__cave_complete "cave-tmdb-missing" (__cave_arg_pos))'

# cave-top
complete -f  -c cave-top -c stack-top -k -a '(__cave_complete "cave-top" (__cave_arg_pos))'

# cave-unwatched
complete -f  -c cave-unwatched -c stack-unwatched -k -a '(__cave_complete "cave-unwatched" (__cave_arg_pos))'

# cave-version
complete -f  -c cave-version -c stack-version -k -a '(__cave_complete "cave-version" (__cave_arg_pos))'

# cave-watchable
complete -f  -c cave-watchable -c stack-watchable -k -a '(__cave_complete "cave-watchable" (__cave_arg_pos))'

# cave-worktree
complete -f  -c cave-worktree -c stack-worktree -k -a '(__cave_complete "cave-worktree" (__cave_arg_pos))'


function __cave_complete --description 'shared positional group completer for cave-* commands'
    set -l cmd "$argv[1]"
    set -l pos "$argv[2]"

    set -l CONTAINERS (docker ps -a --format '{{.Names}}' 2>/dev/null | sort)
    set -l ARR_APPS radarr sonarr prowlarr
    set -l BUTLER_TASKS clean-updates optimize-database refresh-local-media \
        backup-database garbage-collect-blobs garbage-collect-media \
        clean-cache-files clean-log-files process-assets generate-media-index \
        deep-media-analysis upgrade-media-analysis music-analysis \
        loudness-analysis generate-intro-markers generate-credits-markers \
        generate-ad-markers generate-chapter-thumbs generate-voice-activity \
        refresh-epg refresh-libraries automatic-updates

    # group tokens: | separates alternatives within a group, space separates
    # groups. A group like <container> resolves to the dynamic source.
    set -l spec (__cave_directive "$cmd")
    test -n "$spec"; or return 0

    # Split into groups on unescaped spaces (specs are simple, no quotes).
    set -l groups (string split ' ' -- "$spec")
    set -l group ""
    # Flags (-y|--yes …) match at any position; positional groups by index.
    set -l pos_i 0
    for g in $groups
        if string match -q -- '-*' $g
            # flag group: offered at any position
            for alt in (string split '|' -- $g)
                echo "$alt"
            end
            continue
        end
        set pos_i (math $pos_i + 1)
        if test (math $pos_i - 1) -ne $pos
            continue
        end
        set group "$g"
        break
    end
    test -n "$group"; or return 0

    switch $group
        case '<container>'
            for c in $CONTAINERS
                echo "$c"
            end
        case '<arr-app>'
            for a in $ARR_APPS
                echo "$a"
            end
        case '<butler-task>'
            for t in $BUTLER_TASKS
                echo "$t"
            end
        case '<limit>'
            echo 5
            echo 10
            echo 20
            echo 50
        case '*'
            for alt in (string split '|' -- $group)
                echo "$alt"
            end
    end
end

# Directive lookup: name -> raw # complete: spec (kept in sync by the
# generator; one case-branch per command with a directive).
function __cave_directive --description 'raw # complete: spec for a cave-* command'
    switch "$argv[1]"
        case cave-activity-feed stack-activity-feed
            echo '<limit>'
        case cave-arr stack-arr
            echo '<arr-app> rss-sync|search-missing|unstick|unstick-importing'
        case cave-arr-backlog stack-arr-backlog
            echo 'radarr|sonarr'
        case cave-arr-blocklist stack-arr-blocklist
            echo 'radarr|sonarr'
        case cave-arr-clear-blocklist stack-arr-clear-blocklist
            echo 'radarr|sonarr'
        case cave-arr-import stack-arr-import
            echo 'radarr|sonarr'
        case cave-arr-import-all stack-arr-import-all
            echo 'radarr|sonarr'
        case cave-arr-import-candidates stack-arr-import-candidates
            echo 'radarr|sonarr'
        case cave-arr-import-starvation stack-arr-import-starvation
            echo 'radarr|sonarr'
        case cave-arr-logs stack-arr-logs
            echo 'radarr|sonarr'
        case cave-arr-missing-aired stack-arr-missing-aired
            echo 'radarr|sonarr'
        case cave-arr-queue-errors stack-arr-queue-errors
            echo 'radarr|sonarr'
        case cave-arr-recently-added stack-arr-recently-added
            echo 'radarr|sonarr'
        case cave-arr-toggle-search stack-arr-toggle-search
            echo 'radarr|sonarr|all on|off'
        case cave-arrival-notify stack-arrival-notify
            echo '--dry-run|--no-refresh|--json'
        case cave-container stack-container
            echo '<container> restart|stop|start'
        case cave-cutoff-unmet stack-cutoff-unmet
            echo 'radarr|sonarr'
        case cave-disk-reclaim stack-disk-reclaim
            echo '-y|--yes|--dry-run|--aggressive'
        case cave-import-lists stack-import-lists
            echo 'radarr|sonarr'
        case cave-loop-candidates stack-loop-candidates
            echo 'radarr|sonarr'
        case cave-loop-exclude stack-loop-exclude
            echo '-y|--yes'
        case cave-loop-unmonitor stack-loop-unmonitor
            echo 'radarr|sonarr -y|--yes'
        case cave-nzbdav-delete-failures stack-nzbdav-delete-failures
            echo '-y|--yes'
        case cave-plex stack-plex
            echo 'refresh-libraries|empty-trash|analyze|scan'
        case cave-queue-autofix stack-queue-autofix
            echo '-y|--yes'
        case cave-radarr-prune stack-radarr-prune
            echo '-y|--yes|--dry-run'
        case cave-recent stack-recent
            echo '<limit>'
        case cave-requests stack-requests
            echo '<take>'
        case cave-restart-all stack-restart-all
            echo '-y|--yes'
        case cave-seerr-requests stack-seerr-requests
            echo 'pending|approved|available|all'
        case cave-sonarr-prune stack-sonarr-prune
            echo '-y|--yes|--dry-run'
        case cave-sys-flatpak-updates stack-flatpak-updates
            echo '--apply'
        case cave-sys-journal-size stack-journal-size
            echo '--vacuum-size'
        case cave-sys-pkg-clean-cache stack-pkg-clean-cache
            echo '1|2|3|5|10'
        case cave-sys-pkg-orphans stack-pkg-orphans
            echo '--remove'
        case cave-sys-pkg-update stack-pkg-update
            echo '-y|--yes'
        case cave-unwatched stack-unwatched
            echo '<limit>'
        case '*'
            return 1
    end
end
