#!/usr/bin/env bash
# ============================================================================
# gen-bash-completions.sh — generate bash tab-completions for cave-* commands
# ============================================================================
# Sources the shared metadata parser (functions/__metadata.sh), the single
# source of truth for the cave-* command surface also used by cave-help
# and stack-tui. It scans bash/functions/cave-*.sh for:
#   - function definitions:   cave-<name>() {
#   - completion directives:  # complete: <group1>|<alt> <group2> ... [--flags]
#
# Directive syntax (one per function, as the FIRST line of its body —
# a directive in the help comment above the definition is not picked up):
#   # complete: radarr|sonarr|all on|off
#   # complete: -y|--yes
#   # complete: <container>            (dynamic: docker ps -a names)
#   # complete: <arr-app>              (dynamic: radarr sonarr prowlarr)
#
# Groups are positional: group N completes argument N. Groups starting with
# '-' are flag groups offered at any position. '<name>' in angle brackets is
# a dynamic source.
#
# Output: bash/completions/cave-completions.sh
#   --check: regenerate to temp and diff; exit 1 if out of date.
#
# Usage:
#   bash/scripts/gen-bash-completions.sh            # write
#   bash/scripts/gen-bash-completions.sh --check    # verify
# ============================================================================
set -euo pipefail

# Byte-order sorting end to end: the generated command list must be
# identical on every machine regardless of locale. `sort` under en_US
# collates punctuation away (stack-arr-logs < stack-arrival-notify) while
# C.UTF-8 keeps bytes (stack-arr-logs < stack-arrival-notify is reversed:
# '-' sorts before 'i'), so a name added in one locale would silently drift
# under the other and fail the --check gate in CI (found 2026-09-03 with
# stack-arrival-notify).
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
FN_DIR="$(cd "$SCRIPT_DIR/../functions" && pwd)"
OUT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/completions"
OUT_FILE="$OUT_DIR/cave-completions.sh"
CHECK=false
[ "${1:-}" = "--check" ] && CHECK=true

mkdir -p "$OUT_DIR"

# ----------------------------------------------------------------------------
# Collect function definitions and directives from the shared metadata parser
# (functions/__metadata.sh) so completions never drift from the other
# surfaces (stack-help, stack-tui). One TSV record per function:
#   name<TAB>category<TAB>desc<TAB>danger<TAB>complete<TAB>help
# ----------------------------------------------------------------------------
source "$SCRIPT_DIR/../functions/__metadata.sh"

declare -A CMDS      # name -> 1
declare -A DIRECTIVE # name -> raw directive args

# NB: parse with `cut`, not `read` — tab is IFS whitespace, so read would
# collapse the empty complete field of directive-less functions and shift
# the help text into it.
while IFS= read -r _line; do
    [ -n "$_line" ] || continue
    name="$(cut -f1 <<<"$_line")"
    complete="$(cut -f5 <<<"$_line")"
    CMDS["$name"]=1
    [ -n "$complete" ] && DIRECTIVE["$name"]="$complete"
done < <(__stack_metadata)

if [ "${#CMDS[@]}" -eq 0 ]; then
    echo "ERROR: no cave-* functions found in $FN_DIR" >&2
    exit 1
fi

# Alias map: stack-<name> -> cave-<name> (and cave-sys-<name>), parsed from
# the generated bash/_aliases.sh (D21) so completions never drift from the
# alias layer. Lines look like:  stack-arr-backlog() { cave-arr-backlog "$@"; }
ALIASES="$REPO_DIR/bash/_aliases.sh"
declare -A ALIAS_OF   # cave-name -> stack-name (reverse map)
while IFS= read -r _al; do
    [[ "$_al" =~ ^(stack-[a-z0-9-]+)\(\)\ \{\ (cave-[a-z0-9-]+)\ \"\$@\"\;\ \}$ ]] && \
        ALIAS_OF["${BASH_REMATCH[2]}"]="${BASH_REMATCH[1]}"
done < "$ALIASES"

# ----------------------------------------------------------------------------
# Build the generated completion file
# ----------------------------------------------------------------------------
TMP="$(mktemp)"
{
    cat <<'HDR'
# ============================================================================
# cave-completions.sh — GENERATED by gen-bash-completions.sh — do not edit
# ============================================================================
# Regenerate:  bash/scripts/gen-bash-completions.sh
# Verify:      bash/scripts/gen-bash-completions.sh --check
# Loaded automatically by bash/cave-scripts.sh.
# ============================================================================
# shellcheck disable=SC2207

__stack_complete() {
    local cur cmd pos
    cur="${COMP_WORDS[COMP_CWORD]}"
    cmd="${COMP_WORDS[0]}"
    pos=$((COMP_CWORD - 1))   # 0-based index of the word being completed

    # Dynamic sources
    local CONTAINERS
    CONTAINERS=$(docker ps -a --format '{{.Names}}' 2>/dev/null | sort)
    local ARR_APPS="radarr sonarr prowlarr"
    local BUTLER_TASKS="clean-updates optimize-database refresh-local-media\n    backup-database garbage-collect-blobs garbage-collect-media\n    clean-cache-files clean-log-files process-assets generate-media-index\n    deep-media-analysis upgrade-media-analysis music-analysis\n    loudness-analysis generate-intro-markers generate-credits-markers\n    generate-ad-markers generate-chapter-thumbs generate-voice-activity\n    refresh-epg refresh-libraries automatic-updates"
    BUTLER_TASKS=$(printf '%b' "$BUTLER_TASKS" | tr '\n' ' ')

    case "$cmd" in
HDR

    for fn in $(printf '%s\n' "${!CMDS[@]}" | sort); do
        # Dual-name branches: the cave-* command and its permanent stack-*
        # alias (D21) complete identically. The alias is a real function
        # (_aliases.sh) so COMP_WORDS[0] can be either spelling. cave-sys-*
        # aliases map stack-X -> cave-sys-X, so the reverse map is used.
        alias="${ALIAS_OF[$fn]:-}"
        if [ -n "$alias" ]; then
            echo "        $fn|$alias)"
        else
            echo "        $fn)"
        fi
        spec="${DIRECTIVE[$fn]:-}"
        if [ -z "$spec" ]; then
            echo "            ;;"
            continue
        fi
        read -r -a groups <<< "$spec"
        flags=""
        gi=0
        for g in "${groups[@]}"; do
            case "$g" in
                -*)
                    # flag group: split alternates (-y|--yes -> -y --yes)
                    fwords="${g//|/ }"
                    flags="$flags $fwords"
                    ;;
                '<container>')
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "$CONTAINERS" -- "$cur")); return 0; fi\n' "$((gi + 1))"
                    gi=$((gi + 1))
                    ;;
                '<arr-app>')
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "$ARR_APPS" -- "$cur")); return 0; fi\n' "$((gi + 1))"
                    gi=$((gi + 1))
                    ;;
                '<butler-task>')
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "$BUTLER_TASKS" -- "$cur")); return 0; fi\n' "$((gi + 1))"
                    gi=$((gi + 1))
                    ;;
                *)
                    words="${g//|/ }"
                    printf '            if [ $pos -eq %d ]; then COMPREPLY=($(compgen -W "%s" -- "$cur")); return 0; fi\n' "$((gi + 1))" "$words"
                    gi=$((gi + 1))
                    ;;
            esac
        done
        if [ -n "$flags" ]; then
            printf '            COMPREPLY=($(compgen -W "%s" -- "$cur")); return 0;\n' "$flags"
        fi
        if [ -n "$flags" ] || [ "$gi" -gt 0 ]; then
            echo "            return 0;"
        fi
        echo "            ;;"
    done

    cat <<'FTR'
    esac

    # Unknown command (no directive branch matched) — offer command names.
    COMPREPLY=($(compgen -W "__ALL_CMDS__" -- "$cur"))
}

complete -F __stack_complete -o bashdefault -o default -o nospace __STACK_CMDS__
FTR
} > "$TMP"

# Substitute the command list into the footer (kept out of the heredoc so the
# generator never has to escape the list). Both spellings are registered:
# the cave-* names and their stack-* aliases (D21) all complete via the same
# function, and the unknown-command fallback offers both sets.
CMDS_AND_ALIASES="$(printf '%s\n' "${!CMDS[@]}" | sort | tr '\n' ' ')"
CMDS_AND_ALIASES="$CMDS_AND_ALIASES $(printf '%s\n' "${ALIAS_OF[@]}" | sort | tr '\n' ' ')"
CMDS_AND_ALIASES="$(printf '%s\n' $CMDS_AND_ALIASES | sort -u | tr '\n' ' ' | sed 's/ $//')"
sed -i "s/__ALL_CMDS__/${CMDS_AND_ALIASES//&/\\&}/" "$TMP"
sed -i "s/__STACK_CMDS__/${CMDS_AND_ALIASES//&/\\&}/" "$TMP"

# ----------------------------------------------------------------------------
# Write or verify
# ----------------------------------------------------------------------------
if [ "$CHECK" = true ]; then
    if [ ! -f "$OUT_FILE" ]; then
        echo "FAIL: $OUT_FILE missing — run gen-bash-completions.sh to generate it." >&2
        rm -f "$TMP"
        exit 1
    fi
    if ! diff -q "$TMP" "$OUT_FILE" >/dev/null 2>&1; then
        echo "FAIL: $OUT_FILE is out of date with the function files." >&2
        echo "  Regenerate: bash/scripts/gen-bash-completions.sh" >&2
        rm -f "$TMP"
        exit 1
    fi
    echo "OK: $OUT_FILE is current."
else
    mv "$TMP" "$OUT_FILE"
    echo "Wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines, ${#CMDS[@]} commands)."
fi
