#!/usr/bin/env bash
# ============================================================================
# gen-fish-completions.sh — generate fish tab-completions for cave-* commands
# ============================================================================
# Consumes the SHARED metadata parser (bash/functions/__metadata.sh — the one
# implementation also used by cave-help, gen-bash-completions.sh, the zsh
# generator and the TUI), pointed at the fish functions tree, so fish
# completions can never drift from the other surfaces. Directive syntax is
# identical to bash/zsh:
#
#   # complete: radarr|sonarr|all on|off     (groups are positional)
#   # complete: -y|--yes                     (flag group, offered at any pos)
#   # complete: <container> <arr-app> ...    (dynamic sources)
#
# Group N completes argument N. Output: fish/completions/cave-completions.fish
#   --check: regenerate to temp and diff; exit 1 if out of date.
#
# Usage:
#   fish/scripts/gen-fish-completions.sh            # write
#   fish/scripts/gen-fish-completions.sh --check    # verify
# ============================================================================
set -euo pipefail

export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
FISH_DIR="$REPO_DIR/fish"
FN_DIR="$FISH_DIR/functions"
OUT_DIR="$FISH_DIR/completions"
OUT_FILE="$OUT_DIR/cave-completions.fish"
CHECK=false
[ "${1:-}" = "--check" ] && CHECK=true

mkdir -p "$OUT_DIR"

# ----------------------------------------------------------------------------
# Collect function definitions and directives from the shared metadata parser,
# pointed at the fish tree: one TSV record per function:
#   name<TAB>category<TAB>desc<TAB>danger<TAB>complete<TAB>help
# ----------------------------------------------------------------------------
source "$REPO_DIR/bash/functions/__metadata.sh"

declare -A CMDS      # name -> 1
declare -A DIRECTIVE # name -> raw directive args

while IFS= read -r _line; do
    [ -n "$_line" ] || continue
    name="$(cut -f1 <<<"$_line")"
    complete="$(cut -f5 <<<"$_line")"
    CMDS["$name"]=1
    [ -n "$complete" ] && DIRECTIVE["$name"]="$complete"
done < <(__stack_metadata "$FN_DIR" fish)

if [ "${#CMDS[@]}" -eq 0 ]; then
    echo "ERROR: no cave-* functions found in $FN_DIR" >&2
    exit 1
fi

# Alias map (D21): parse the shared bash/_aliases.sh — lines look like
#   stack-arr-backlog() { cave-arr-backlog "$@"; }
ALIASES="$REPO_DIR/bash/_aliases.sh"
declare -A ALIAS_OF   # cave-name -> stack-name (reverse map)
while IFS= read -r _al; do
    [[ "$_al" =~ ^(stack-[a-z0-9-]+)\(\)\ \{\ (cave-[a-z0-9-]+)\ \"\$@\"\;\ \}$ ]] && \
        ALIAS_OF["${BASH_REMATCH[2]}"]="${BASH_REMATCH[1]}"
done < "$ALIASES"

# ----------------------------------------------------------------------------
# Build the generated completion file. fish completion mechanics:
#   complete -c <cmd> -n '__fish_seen_subcommand_from …' …  is overkill here;
#   the positional contract is implemented with __fish_use_subcommand +
#   a per-position helper counting previous non-flag args (the same
#   corrected positional contract as the bash/zsh generators).
# ----------------------------------------------------------------------------
TMP="$(mktemp)"
{
    cat <<'HDR'
# ============================================================================
# cave-completions.fish — GENERATED by gen-fish-completions.sh — do not edit
# ============================================================================
# Regenerate:  fish/scripts/gen-fish-completions.sh
# Verify:      fish/scripts/gen-fish-completions.sh --check
# Loaded automatically by fish/cave-scripts.fish.
#
# Directive groups are positional: group N completes argument N (the same
# corrected contract as the bash completions since the 2026-09-05 fix).
# <name> groups are dynamic sources resolved lazily at completion time.
# ============================================================================

function __cave_arg_pos --description '0-based index of the argument being completed (flags skipped)'
    set -l tokens (commandline -opc)
    set -e tokens[1]
    set -l pos 0
    for t in $tokens
        switch $t
            case '-*'
            case '*'
                set pos (math $pos + 1)
        end
    end
    # When completing a new word the cursor sits on an empty token; the
    # tokens list already excludes the command itself, so the position of
    # the argument being completed is (count of prior non-flag args).
    echo $pos
end

HDR

    # Emit one conditional block per command (dual-name: cave-* + stack-*).
    for fn in $(printf '%s\n' "${!CMDS[@]}" | sort); do
        directive="${DIRECTIVE[$fn]:-}"
        alias_name="${ALIAS_OF[$fn]:-}"
        if [ -n "$alias_name" ]; then
            pair="$fn|$alias_name"
        else
            pair="$fn"
        fi
        cond=""
        IFS='|' read -ra names <<< "$pair"
        for n in "${names[@]}"; do
            cond="$cond -c $n"
        done
        echo "# $fn"
        echo "complete -f $cond -k -a '(__cave_complete \"$fn\" (__cave_arg_pos))'"
        echo ""
    done

    cat <<'FTR'

function __cave_complete --description 'shared positional group completer for cave-* commands'
    set -l cmd "$argv[1]"
    set -l pos "$argv[2]"

    set -l CONTAINERS (docker ps -a --format '{{.Names}}' 2>/dev/null | sort)
    set -l ARR_APPS radarr sonarr prowlarr
    set -l BUTLER_TASKS clean-updates optimize-database refresh-local-media \
        backup-database garbage-collect-blobs garbage-collect-media \
        clean-cache-files clean-log-files process-assets generate-media-index \
        deep-media-analysis upgrade-media-analysis music-analysis \
        loudness-analysis generate-intro-markers generate-credits-markers \
        generate-ad-markers generate-chapter-thumbs generate-voice-activity \
        refresh-epg refresh-libraries automatic-updates

    # group tokens: | separates alternatives within a group, space separates
    # groups. A group like <container> resolves to the dynamic source.
    set -l spec (__cave_directive "$cmd")
    test -n "$spec"; or return 0

    # Split into groups on unescaped spaces (specs are simple, no quotes).
    set -l groups (string split ' ' -- "$spec")
    set -l group ""
    # Flags (-y|--yes …) match at any position; positional groups by index.
    set -l pos_i 0
    for g in $groups
        if string match -q -- '-*' $g
            # flag group: offered at any position
            for alt in (string split '|' -- $g)
                echo "$alt"
            end
            continue
        end
        set pos_i (math $pos_i + 1)
        if test (math $pos_i - 1) -ne $pos
            continue
        end
        set group "$g"
        break
    end
    test -n "$group"; or return 0

    switch $group
        case '<container>'
            for c in $CONTAINERS
                echo "$c"
            end
        case '<arr-app>'
            for a in $ARR_APPS
                echo "$a"
            end
        case '<butler-task>'
            for t in $BUTLER_TASKS
                echo "$t"
            end
        case '<limit>'
            echo 5
            echo 10
            echo 20
            echo 50
        case '*'
            for alt in (string split '|' -- $group)
                echo "$alt"
            end
    end
end

# Directive lookup: name -> raw # complete: spec (kept in sync by the
# generator; one case-branch per command with a directive).
function __cave_directive --description 'raw # complete: spec for a cave-* command'
    switch "$argv[1]"
FTR

    for fn in $(printf '%s\n' "${!CMDS[@]}" | sort); do
        directive="${DIRECTIVE[$fn]:-}"
        [ -n "$directive" ] || continue
        alias_name="${ALIAS_OF[$fn]:-}"
        echo "        case $fn${alias_name:+ $alias_name}"
        echo "            echo '$directive'"
    done

    cat <<'FTR2'
        case '*'
            return 1
    end
end
FTR2

} > "$TMP"

if [ "$CHECK" = true ]; then
    if ! diff -q "$TMP" "$OUT_FILE" >/dev/null 2>&1; then
        echo "FAIL: fish/completions/cave-completions.fish is out of date" >&2
        echo "  Regenerate: fish/scripts/gen-fish-completions.sh" >&2
        rm -f "$TMP"
        exit 1
    fi
    rm -f "$TMP"
    echo "OK: fish/completions/cave-completions.fish is current."
else
    mv "$TMP" "$OUT_FILE"
    echo "Wrote fish/completions/cave-completions.fish ($(grep -c '^complete ' "$OUT_FILE") completion rules)."
fi
