#!/usr/bin/env bash
# ============================================================================
# gen-zsh-completions.sh — generate zsh compdef completions for cave-* commands
# ============================================================================
# Consumes the SHARED metadata parser (bash/functions/__metadata.sh — the one
# implementation also used by cave-help, gen-bash-completions.sh and the
# TUI), pointed at the zsh functions tree, so zsh completions can never drift
# from the other surfaces. Directive syntax is identical to bash:
#
#   # complete: radarr|sonarr|all on|off     (groups are positional)
#   # complete: -y|--yes                     (flag group, offered at any pos)
#   # complete: <container> <arr-app> ...    (dynamic sources)
#
# Group N completes argument N — the same corrected positional contract the
# bash generator ships since the 2026-09-05 off-by-one fix (bash previously
# fired group N at argument N+1).
#
# Output: zsh/completions/_cave-cmd — a #compdef file autoloaded from fpath
# by zsh/cave-scripts.zsh.
#   --check: regenerate to temp and diff; exit 1 if out of date.
#
# Usage:
#   zsh/scripts/gen-zsh-completions.sh            # write
#   zsh/scripts/gen-zsh-completions.sh --check    # verify
# ============================================================================
set -euo pipefail

export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ZSH_DIR="$REPO_DIR/zsh"
FN_DIR="$ZSH_DIR/functions"
OUT_DIR="$ZSH_DIR/completions"
OUT_FILE="$OUT_DIR/_cave-cmd"
CHECK=false
[ "${1:-}" = "--check" ] && CHECK=true

mkdir -p "$OUT_DIR"

# ----------------------------------------------------------------------------
# Collect function definitions and directives from the shared metadata parser,
# pointed at the zsh tree: one TSV record per function:
#   name<TAB>category<TAB>desc<TAB>danger<TAB>complete<TAB>help
# ----------------------------------------------------------------------------
source "$REPO_DIR/bash/functions/__metadata.sh"

declare -A CMDS      # name -> 1
declare -A DIRECTIVE # name -> raw directive args

while IFS= read -r _line; do
    [ -n "$_line" ] || continue
    name="$(cut -f1 <<<"$_line")"
    complete="$(cut -f5 <<<"$_line")"
    CMDS["$name"]=1
    [ -n "$complete" ] && DIRECTIVE["$name"]="$complete"
done < <(__stack_metadata "$FN_DIR" zsh)

if [ "${#CMDS[@]}" -eq 0 ]; then
    echo "ERROR: no cave-* functions found in $FN_DIR" >&2
    exit 1
fi

# Alias map (D21): parse the shared bash/_aliases.sh — lines look like
#   stack-arr-backlog() { cave-arr-backlog "$@"; }
ALIASES="$REPO_DIR/bash/_aliases.sh"
declare -A ALIAS_OF   # cave-name -> stack-name (reverse map)
while IFS= read -r _al; do
    [[ "$_al" =~ ^(stack-[a-z0-9-]+)\(\)\ \{\ (cave-[a-z0-9-]+)\ \"\$@\"\;\ \}$ ]] && \
        ALIAS_OF["${BASH_REMATCH[2]}"]="${BASH_REMATCH[1]}"
done < "$ALIASES"

# ----------------------------------------------------------------------------
# Build the generated compdef file. Mirrors the bash generator's structure
# (__stack_complete) with zsh-native mechanics:
#   - zsh indexes the line with $words (1-based, command at [1]) and
#     $CURRENT (index of the word being completed); the first argument sits
#     at CURRENT=2, so arg N has pos = CURRENT - 2 (0-based, arg1 -> 0).
#   - compadd replaces compgen -W ... -- "$cur": it filters by the current
#     word automatically.
#   - dual-name branches (cave-X|stack-X) and the unknown-command fallback
#     mirror bash exactly.
# ----------------------------------------------------------------------------
TMP="$(mktemp)"
{
    cat <<'HDR'
#compdef __STACK_CMDS__

# ============================================================================
# _cave-cmd — GENERATED by gen-zsh-completions.sh — do not edit
# ============================================================================
# Regenerate:  zsh/scripts/gen-zsh-completions.sh
# Verify:      zsh/scripts/gen-zsh-completions.sh --check
# Loaded automatically by zsh/cave-scripts.zsh (fpath + compinit autoload).
#
# Directive groups are positional: group N completes argument N (the same
# corrected contract as the bash completions since the 2026-09-05 fix).
# <name> groups are dynamic sources resolved lazily.
# ============================================================================

_cave-cmd() {
    local cur cmd pos
    cur="${words[CURRENT]}"
    cmd="${words[1]}"
    pos=$((CURRENT - 2))    # 0-based arg index being completed (arg1 -> 0)

    # Dynamic sources
    local -a CONTAINERS
    CONTAINERS=(${(f)"$(docker ps -a --format '{{.Names}}' 2>/dev/null)"})
    local -a ARR_APPS BUTLER_TASKS
    ARR_APPS=(radarr sonarr prowlarr)
    BUTLER_TASKS=(clean-updates optimize-database refresh-local-media \
        backup-database garbage-collect-blobs garbage-collect-media \
        clean-cache-files clean-log-files process-assets generate-media-index \
        deep-media-analysis upgrade-media-analysis music-analysis \
        loudness-analysis generate-intro-markers generate-credits-markers \
        generate-ad-markers generate-chapter-thumbs generate-voice-activity \
        refresh-epg refresh-libraries automatic-updates)

    case "$cmd" in
HDR

    for fn in $(printf '%s\n' "${!CMDS[@]}" | sort); do
        alias="${ALIAS_OF[$fn]:-}"
        if [ -n "$alias" ]; then
            echo "        $fn|$alias)"
        else
            echo "        $fn)"
        fi
        spec="${DIRECTIVE[$fn]:-}"
        if [ -z "$spec" ]; then
            echo "            ;;"
            continue
        fi
        read -r -a groups <<< "$spec"
        flags=""
        gi=0
        for g in "${groups[@]}"; do
            case "$g" in
                -*)
                    # flag group: split alternates (-y|--yes -> -y --yes)
                    fwords="${g//|/ }"
                    flags="$flags $fwords"
                    ;;
                '<container>')
                    printf '            if [ $pos -eq %d ]; then compadd -- $CONTAINERS; return 0; fi\n' "$gi"
                    gi=$((gi + 1))
                    ;;
                '<arr-app>')
                    printf '            if [ $pos -eq %d ]; then compadd -- $ARR_APPS; return 0; fi\n' "$gi"
                    gi=$((gi + 1))
                    ;;
                '<butler-task>')
                    printf '            if [ $pos -eq %d ]; then compadd -- $BUTLER_TASKS; return 0; fi\n' "$gi"
                    gi=$((gi + 1))
                    ;;
                \<*\>)
                    # Free-form argument (<limit>/<take> = numeric count, not an
                    # enumerable word list). Consume the position so later
                    # groups stay aligned, but offer no candidates.
                    gi=$((gi + 1))
                    ;;
                *)
                    words="${g//|/ }"
                    printf '            if [ $pos -eq %d ]; then compadd -- %s; return 0; fi\n' "$gi" "$words"
                    gi=$((gi + 1))
                    ;;
            esac
        done
        if [ -n "$flags" ]; then
            printf '            compadd -- %s; return 0;\n' "$flags"
        fi
        if [ -n "$flags" ] || [ "$gi" -gt 0 ]; then
            echo "            return 0;"
        fi
        echo "            ;;"
    done

    cat <<'FTR'
    esac

    # Unknown command (no directive branch matched) — offer command names.
    compadd -- __ALL_CMDS__
}
FTR
} > "$TMP"

# Substitute the command list into the footer and the #compdef header. Both
# spellings are registered: cave-* names and their stack-* aliases (D21) all
# complete via the same function.
CMDS_AND_ALIASES="$(printf '%s\n' "${!CMDS[@]}" | sort | tr '\n' ' ')"
CMDS_AND_ALIASES="$CMDS_AND_ALIASES $(printf '%s\n' "${ALIAS_OF[@]}" | sort | tr '\n' ' ')"
CMDS_AND_ALIASES="$(printf '%s\n' $CMDS_AND_ALIASES | sort -u | tr '\n' ' ' | sed 's/ $//')"
sed -i "s/__ALL_CMDS__/${CMDS_AND_ALIASES//&/\\&}/" "$TMP"
sed -i "s/__STACK_CMDS__/${CMDS_AND_ALIASES//&/\\&}/" "$TMP"

# ----------------------------------------------------------------------------
# Write or verify
# ----------------------------------------------------------------------------
if [ "$CHECK" = true ]; then
    if [ ! -f "$OUT_FILE" ]; then
        echo "FAIL: $OUT_FILE missing — run gen-zsh-completions.sh to generate it." >&2
        rm -f "$TMP"
        exit 1
    fi
    if ! diff -q "$TMP" "$OUT_FILE" >/dev/null 2>&1; then
        echo "FAIL: $OUT_FILE is out of date with the function files." >&2
        echo "  Regenerate: zsh/scripts/gen-zsh-completions.sh" >&2
        rm -f "$TMP"
        exit 1
    fi
    echo "OK: $OUT_FILE is current."
else
    mv "$TMP" "$OUT_FILE"
    echo "Wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines, ${#CMDS[@]} commands)."
fi
