#!/usr/bin/env bash
# render-theme.sh — shared theme-file generator, factored out of
# build-themes.sh so both the fixed 6-palette set AND `hyprtheme auto`
# (matugen-derived, wallpaper-matched) can produce identical-shape theme
# directories from one source of truth. Sourced, not run directly.
#
# render_theme NAME DESC BG BG_ALT BORDER FG MUTED DIM ACCENT RED ORANGE YELLOW GREEN BLUE PURPLE
#
# Writes colors.properties, waybar.css, wofi.css, swaync.css, hyprlock.conf,
# alacritty-colors.toml into $THEMES/$NAME/ (caller creates $THEMES/$NAME and
# handles wallpaper.png itself — gradient-generated for the fixed palettes,
# copied from the source image for matugen mode).

rgb() { # hex → "r, g, b"
    local h="$1"
    printf "%d, %d, %d" "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}

render_theme() {
    local NAME="$1" DESC="$2" BG="$3" BG_ALT="$4" BORDER="$5" FG="$6" MUTED="$7" \
          DIM="$8" ACCENT="$9" RED="${10}" ORANGE="${11}" YELLOW="${12}" \
          GREEN="${13}" BLUE="${14}" PURPLE="${15}"
    local D="$THEMES/$NAME"
    mkdir -p "$D"

    # ── colors.properties ────────────────────────────────────────
    {
        echo "NAME=$NAME"
        echo "DESC=$DESC"
        echo "BG=$BG"; echo "BG_ALT=$BG_ALT"; echo "BORDER=$BORDER"
        echo "FG=$FG"; echo "MUTED=$MUTED"; echo "DIM=$DIM"
        echo "ACCENT=$ACCENT"; echo "RED=$RED"; echo "ORANGE=$ORANGE"
        echo "YELLOW=$YELLOW"; echo "GREEN=$GREEN"; echo "BLUE=$BLUE"; echo "PURPLE=$PURPLE"
    } > "$D/colors.properties"

    sed_theme() { # $1 = template heredoc already in stdin
        sed -e "s|@NAME@|$NAME|g" -e "s|@DESC@|$DESC|g" \
            -e "s|@BG@|$BG|g" -e "s|@BG_ALT@|$BG_ALT|g" -e "s|@BORDER@|$BORDER|g" \
            -e "s|@FG@|$FG|g" -e "s|@MUTED@|$MUTED|g" -e "s|@DIM@|$DIM|g" \
            -e "s|@ACCENT@|$ACCENT|g" -e "s|@RED@|$RED|g" -e "s|@ORANGE@|$ORANGE|g" \
            -e "s|@YELLOW@|$YELLOW|g" -e "s|@GREEN@|$GREEN|g" -e "s|@BLUE@|$BLUE|g" \
            -e "s|@PURPLE@|$PURPLE|g"
    }

    # ── waybar.css ───────────────────────────────────────────────
    cat <<'TMPL' | sed_theme > "$D/waybar.css"
/* @NAME@ — @DESC@ · generated by render-theme.sh
 * Floating rounded-pill bar: paired with `layerrule = blur/ignore_alpha, waybar`
 * in hyprland.conf so the semi-transparent background actually blurs. */
* {
    border: none;
    border-radius: 0;
    font-family: "JetBrainsMono Nerd Font";
    font-size: 15.5px;
    font-weight: 500;
    min-height: 0;
}

window#waybar {
    background: alpha(#@BG@, 0.82);
    color: #@FG@;
    border-radius: 14px;
    border: 1px solid alpha(#@ACCENT@, 0.35);
    box-shadow: 0 2px 14px alpha(#000000, 0.35);
}

.modules-left, .modules-center, .modules-right { background: transparent; }

/* shared pill treatment (systemd-failed-units excluded: it needs to
 * collapse to nothing when there's nothing failed, see below) */
#workspaces, #window, #privacy, #temperature, #cpu, #custom-gpu, #memory,
#network, #custom-weather, #mpris, #custom-cava, #pulseaudio, #bluetooth,
#power-profiles-daemon, #custom-updates, #custom-stack, #custom-idle,
#custom-record, #custom-nightlight, #tray, #custom-power, #clock {
    margin: 6px 3px;
    padding: 0 13px;
    border-radius: 10px;
    background: alpha(#@BG_ALT@, 0.55);
    transition: background 150ms ease, color 150ms ease;
}

#workspaces { margin-left: 8px; padding: 3px; background: alpha(#@BG_ALT@, 0.35); }
#workspaces button {
    padding: 0 13px;
    margin: 0 2px;
    border-radius: 8px;
    color: #@MUTED@;
    background: transparent;
    transition: all 150ms ease;
}
#workspaces button:hover { color: #@FG@; background: alpha(#@ACCENT@, 0.25); }
#workspaces button.active {
    color: #@BG@;
    background: #@ACCENT@;
    box-shadow: 0 0 10px alpha(#@ACCENT@, 0.65);
}
#workspaces button.urgent { color: #@BG@; background: #@RED@; }

#window { min-width: 224px; color: #@MUTED@; background: transparent; }

/* per-module accent hues (unchanged from before, now on pills) */
#custom-weather { color: #@BLUE@; }
#custom-gpu { color: #@ORANGE@; }
#custom-gpu.high { color: #@RED@; font-weight: bold; }
#custom-gpu.offline { color: #@DIM@; }
#privacy { color: #@RED@; }
#temperature { color: #@YELLOW@; }
#cpu { color: #@ORANGE@; }
#memory { color: #@GREEN@; }
#network { color: #@GREEN@; }
#mpris { color: #@ORANGE@; }
#custom-cava { color: #@ACCENT@; letter-spacing: -1px; }
#pulseaudio, #pulseaudio\.mic { color: #@PURPLE@; }
#bluetooth { color: #@BLUE@; }
#power-profiles-daemon { color: #@GREEN@; }
#custom-power { color: #@RED@; }
#clock { margin-right: 8px; color: #@FG@; font-weight: 600; }

#custom-updates { color: #@MUTED@; }
#custom-updates.pending { color: #@YELLOW@; }
#custom-updates.updated { color: #@GREEN@; }

#custom-stack { color: #@MUTED@; opacity: 0.55; }
#custom-stack.open { opacity: 1; color: #@ACCENT@; }
#custom-idle { color: #@MUTED@; }
#custom-idle.on { color: #@GREEN@; }
#custom-record { color: #@MUTED@; }
#custom-record.recording { color: #@RED@; font-weight: bold; }
#custom-nightlight { color: #@MUTED@; }
#custom-nightlight.active { color: #@YELLOW@; }
#custom-weather.offline { color: #@DIM@; }

#bluetooth.off { color: #@DIM@; }
#bluetooth.on { color: #@BLUE@; }
#bluetooth.connected { color: #@GREEN@; }

/* systemd-failed-units: hide-on-ok empties the label but doesn't remove the
 * widget from layout, so default to a collapsed/invisible pill and only pop
 * it into an attention-grabbing red pill for the .degraded (has failures)
 * state — safer than relying on a maybe-unapplied ".ok" class existing. */
#systemd-failed-units { padding: 0; margin: 0; background: transparent; min-width: 0; color: #@RED@; }
#systemd-failed-units.degraded {
    padding: 0 13px;
    margin: 6px 3px;
    border-radius: 10px;
    background: alpha(#@BG_ALT@, 0.55);
}

/* subtle hover-lift on every clickable pill */
#custom-weather:hover, #network:hover, #pulseaudio:hover, #pulseaudio\.mic:hover,
#bluetooth:hover, #mpris:hover, #custom-cava:hover, #cpu:hover, #custom-gpu:hover,
#memory:hover, #custom-updates:hover, #custom-stack:hover, #custom-idle:hover,
#custom-record:hover, #custom-nightlight:hover, #custom-power:hover, #clock:hover,
#power-profiles-daemon:hover {
    background: alpha(#@ACCENT@, 0.18);
}

#tray { padding: 0 8px; }

tooltip {
    background: alpha(#@BG_ALT@, 0.95);
    border: 1px solid #@ACCENT@;
    border-radius: 10px;
    color: #@FG@;
}
TMPL

    # ── wofi.css ─────────────────────────────────────────────────
    cat <<'TMPL' | sed_theme > "$D/wofi.css"
/* @NAME@ — @DESC@ · generated by render-theme.sh */
* { font-family: "MesloLGS Nerd Font", sans-serif; font-size: 15px; }

window {
    background-color: #@BG@;
    border: 2px solid #@ACCENT@;
    border-radius: 16px;
}

#input {
    margin: 14px;
    padding: 10px 14px;
    border-radius: 10px;
    background-color: #@BG_ALT@;
    color: #@FG@;
    border: none;
    outline: none;
}

#inner-box { margin: 4px 14px 14px 14px; background-color: transparent; }
#outer-box { background-color: transparent; }
#scroll { margin: 0; }
#text { color: #@FG@; }

#entry { padding: 8px 10px; border-radius: 10px; margin: 2px 0; }
#entry:selected { background-color: #@ACCENT@; }
#entry:selected #text { color: #@BG@; font-weight: bold; }
TMPL

    # ── swaync.css ───────────────────────────────────────────────
    cat <<'TMPL' | sed_theme > "$D/swaync.css"
/* @NAME@ — @DESC@ · generated by render-theme.sh */
* { font-family: "MesloLGS Nerd Font", sans-serif; font-size: 15px; }

.control-center {
    background: #@BG@;
    border: 1px solid #@BORDER@;
    border-radius: 12px;
}

.notification-row { margin: 4px 6px; outline: none; }
.control-center .notification-row { background: transparent; }

.notification {
    background: #@BG_ALT@;
    border: 1px solid #@BORDER@;
    border-radius: 10px;
}
.notification-content { margin: 8px 10px; }
.notification-default-action, .close-button { color: #@FG@; background: transparent; }
.close-button:hover { background: #@RED@; color: #@BG@; }

.title, .summary { color: #@FG@; }
.time, .body { color: #@MUTED@; }

.control-center-clear-all {
    color: #@FG@;
    background: #@BG_ALT@;
    border: 1px solid #@BORDER@;
    border-radius: 8px;
    margin: 6px;
}
.control-center-clear-all:hover { background: #@RED@; color: #@BG@; }

.widget-buttons > button {
    color: #@FG@;
    background: #@BG_ALT@;
    border: 1px solid #@BORDER@;
    border-radius: 8px;
}

.notification.low { border-color: #@BLUE@; }
.notification.normal { border-color: #@BORDER@; }
.notification.critical { border-color: #@RED@; }
TMPL

    # ── hyprlock.conf ────────────────────────────────────────────
    cat <<TMPL > "$D/hyprlock.conf"
# hyprlock — $NAME ($DESC) · generated by render-theme.sh
general {
    hide_cursor = true
    ignore_empty_input = true
    # grace period is now a CLI flag (see hyprlock invocations); fade is on
    # by default via the animations system.
}

background {
    monitor = HDMI-A-1
    path = $D/wallpaper.png
    color = rgba($(rgb "$BG"), 1.0)
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor = HDMI-A-1
    size = 360, 60
    outline_thickness = 2
    dots_size = 0.20
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba($(rgb "$ACCENT"), 0.9)
    inner_color = rgba($(rgb "$BG"), 0.9)
    font_color = rgba($(rgb "$FG"), 1.0)
    fade_on_empty = true
    check_color = rgba($(rgb "$GREEN"), 1.0)
    fail_color = rgba($(rgb "$RED"), 0.9)
    capslock_color = rgba($(rgb "$YELLOW"), 0.9)
    fail_text = <i>\$FAIL <b>(\$ATTEMPTS)</b></i>
    placeholder_text = <span foreground="##$MUTED">Password…</span>
}

label {
    monitor = HDMI-A-1
    text = \$TIME
    font_family = MesloLGS Nerd Font
    font_size = 42
    color = rgba($(rgb "$FG"), 1.0)
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor = HDMI-A-1
    text = cmd[update:1000] echo "\$(date +'%A, %d %B  %Y')"
    font_family = MesloLGS Nerd Font
    font_size = 16
    color = rgba($(rgb "$MUTED"), 1.0)
    position = 0, 55
    halign = center
    valign = center
}
TMPL

    # ── alacritty-colors.toml (stack-tui terminal theme) ─────────
    cat <<TMPL | sed_theme > "$D/alacritty-colors.toml"
# alacritty terminal colors — @NAME@ (@DESC@) · generated by render-theme.sh
# Copied to ~/.config/alacritty/colors.toml by hyprtheme; imported from the
# static ~/.config/alacritty/alacritty.toml (font/window settings live there).

[colors.primary]
background = "#@BG@"
foreground = "#@FG@"

[colors.cursor]
cursor = "#@ACCENT@"
text = "#@BG@"

[colors.selection]
background = "#@BG_ALT@"
text = "#@FG@"

# normal.blue/bright.cyan = @ACCENT@ deliberately, so stack-tui's header/
# button chrome ("dark blue" bg) and category labels ("light cyan" fg) pick
# up the theme's signature color, same as borders/highlights everywhere else.
[colors.normal]
black   = "#@BG_ALT@"
red     = "#@RED@"
green   = "#@GREEN@"
yellow  = "#@ORANGE@"
blue    = "#@ACCENT@"
magenta = "#@PURPLE@"
cyan    = "#@BLUE@"
white   = "#@MUTED@"

[colors.bright]
black   = "#@DIM@"
red     = "#@RED@"
green   = "#@GREEN@"
yellow  = "#@YELLOW@"
blue    = "#@BLUE@"
magenta = "#@PURPLE@"
cyan    = "#@ACCENT@"
white   = "#@FG@"
TMPL

    unset -f sed_theme
}
